# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5029cafcf3de8e68570967875227c70a6a8f6d1e3bf27d326d2da1a86d4fa33a8c2f6b3b5bc680cbaa66d6bd611eada91814a36202020bb4b82dbc71f85f01ff

test:
  secret_key_base: b1ca5f9a1708978dc0f87a33ecc1615f50109498e874aebedc172bedf4b5050f37f542091314d49c25b649ebd73ca81997200ede4b54e0b19dfc5c0a6bda1fc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
